### PR TITLE
Implement native HDFS functions via the hadoopy module. Fixes #86.

### LINKED ISSUE #86: Lobster breaks if the hadoop mount point detaches and chirp is not enabled.
We are currently reliant on fuse for all master-HDFS interactions. Fuse is finicky. We should implement native HDFS functions.

### PR DESCRIPTION
**Pull request by annawoodard**
This is not a very elegant solution-- I don't know how to detect HDFS endpoints except testing for a leading ‘hadoop' and making sure that all lobster.fs functions preserve the leading ‘hadoop.' But it works, so I think we should keep it as a starting point. I will merge this PR tomorrow unless there are any objections.

### CODE REVIEW

**Comment by matz-e** [comment]
I like the implementation!  But… there's some functionality already in place to use chirp to check for files when merging etc, see [here](https://github.com/matz-e/lobster/blob/master/lobster/chirp.py) for the implementation and [here](https://github.com/matz-e/lobster/blob/master/lobster/cmssw/job.py#L334) for usage.

I would suggest the following ([before merging, as we should switch to a different development style, IMO](http://nvie.com/posts/a-successful-git-branching-model/)):

* use your module and decorator structure
* add  chirp functionality
* replace chirp module usage with the fs module

I would like to retain chirp usage, as the storage element is not guaranteed to be a local hadoop.  On the other hand, using your module will circumvent another layer of chirp to go through.  In the long term, we maybe should add some SRM capabilities, to not rely on chirp too much.  I think I had mentioned this to Kevin already, too.

**Comment by annawoodard** [comment]
> I like the implementation!  But… there's some functionality already in place to use chirp to check for files when merging etc, see [here](https://github.com/matz-e/lobster/blob/master/lobster/chirp.py) for the implementation and [here](https://github.com/matz-e/lobster/blob/master/lobster/cmssw/job.py#L334) for usage.

Of course I know about the chirp module :). It's very nice, but in my last workflow I could not use it because I was not running a cmsRun executable, so I could not use Chirp (see #85). I've edited #86 for clarity.

> I would suggest the following ([before merging, as we should switch to a different development style, IMO](http://nvie.com/posts/a-successful-git-branching-model/)):

I agree-- let's switch to this development style.

> * use your module and decorator structure
* add  chirp functionality
* replace chirp module usage with the fs module

> I would like to retain chirp usage, as the storage element is not guaranteed to be a local hadoop.  On the other hand, using your module will circumvent another layer of chirp to go through.  In the long term, we maybe should add some SRM capabilities, to not rely on chirp too much.  I think I had mentioned this to Kevin already, too.

Sounds good to me.

**Comment by matz-e** [comment]
The chirp module is used by the JobProvider, so your (non)usage of `cmsRun` does not really matter… None of the chirp module is used on the job.  That's why I'm proposing it should be folded into your new fs module.  Then we should be having several access modes for the data storage (ordered by priority):

* direct via the os module
* via hadoop module
* via chirp
* via srm (in the future)

**Comment by annawoodard** [comment]
But the chirp module won't help you if you don't have a chirp server going.

**Comment by matz-e** [comment]
That's why I'm suggesting folding it into the `fs` module to have all the options :)

The chirp module had a fall-back to local methods, so it didn't really require a running chirp server.

**Comment by annawoodard** [comment]
But the local methods would fail if the storage element was in HDFS. I was just clarifying why I disagreed with the statement that the 'usage of cmsRun does not matter.'

**Comment by annawoodard** [comment]
As per @matz-e's suggestion, I am closing this PR and re-opening it to merge with the dev branch. I'll open a new issue for @matz-e's suggestion to merge the fs and chirp modules.

**Comment by annawoodard** [comment]
Since we have #91 opened now, and we changed the development model back to merging with the master, I'm going to merge this (again.)

**Pull request merged**
