### PR TITLE
Monitor everything in mainloop

### PR DESCRIPTION
**Pull request by matz-e**
Will hopefully provide a better overview w.r.t. time we spend in either WQ or Lobster.

Broke the fraction plot into two stack plots: one for Lobster, the other for WQ. WQ is setup such that the times should add up to what is called "fetch" for the Lobster plot.

Example:
screen shot 2016-05-27 at 15 02 16

(from [here](http://www.crc.nd.edu/~mwolf3/lobster/ttH/v28/))

### CODE REVIEW

**Comment by klannon** [comment]
I haven't tested it, but the plot looks very nice.

**Comment by matz-e** [comment]
I'm curious how it'll evolve over time…

**Comment by klannon** [comment]
Indeed.  What I'd really like to see is what happens when Lobster/WQ is dealing with 1-2k (or more) workers.  I think Lobster and WQ previously haven't shown any issues running below that scale, but above 1k workers, it seemed like "other" used to dominate things.

**Comment by annawoodard** [comment]
Awesome! Thanks, @matz-e! I think this will take us far in uncovering the mystery load!

**Comment by matz-e** [comment]
Well… we may just see that our database queries need to be more efficient than they currently are…

**Comment by annawoodard** [comment]
Knowledge is power.

**Pull request merged**
