### PR TITLE
Obey the pep-8

### PR DESCRIPTION
**Pull request by matz-e**
This adds a separate test to travis, checking for pep-8 compliance — to ensure our code satisfies common standards.

Filing this PR in part to see what it looks like for PRs?

### CODE REVIEW

**Comment by matz-e** [comment]
OK, this is sub-optimal… but when clicking on "Details" when the checks are shown, the tests are now split up into unit-tests and the style-check!

**Comment by annawoodard** [comment]
This is awesome! Can we tell it to ignore the `cctools-ndcms_mid2016_scale_run` directory?

**Comment by matz-e** [comment]
Yes! From the docs:
```
  --exclude=patterns    exclude files or directories which match these comma
                        separated patterns (default:
                        .svn,CVS,.bzr,.hg,.git,__pycache__,.tox)
```

**Comment by annawoodard** [comment]
Thanks @matz-e!!!!!!! 👏 👏 👏

**Pull request merged**
