### PR TITLE
Send email to user when proxy is going to expire within 24 hours.

### PR DESCRIPTION
**Pull request by WenzhaoLi**
Send email to user when proxy is going to expire within 24 hours.
The email will only be sent once. But every time user renews the proxy, the email will be reset. Which means, if the proxy drops to 24 hours again, another email will be sent, and so forth.

### CODE REVIEW

**Comment by WenzhaoLi** [comment]
These commits have been tested.

**Comment by WenzhaoLi** [comment]
close #521

**Comment by matz-e** [comment]
You should fix there style issues (from the tests):
```
./lobster/commands/process.py:280:53: W291 trailing whitespace
./lobster/commands/process.py:282:77: W291 trailing whitespace
./lobster/commands/process.py:283:122: E251 unexpected spaces around keyword / parameter equals
./lobster/commands/process.py:283:124: E251 unexpected spaces around keyword / parameter equals
```

Something like [flycheck](http://www.flycheck.org/en/latest/) may help you. Seems more of a pain with emacs than with vim…

**Comment by WenzhaoLi** [comment]
Thanks for the info. But I am using Putty.. I will find something compatible with Putty. So how did you get the style debug? Can I get it on Github?

**Comment by matz-e** [comment]
It may work on the command-line, too. I have an equivalent in vim in the terminal. If you click on "Details" by the failed checks, you should be able to find the failed test.

**Comment by WenzhaoLi** [comment]
Got it! Thanks!!

**Comment by klannon** [comment]
I've been running with this branch merged into master for a couple of days now.  No problems and I got my proxy e-mail reminder right on schedule.  I'm going to go ahead and merge this.

**Comment by WenzhaoLi** [comment]
Yes, I set a variable to reset the email. I am glad that it's working. Thanks!

**Pull request merged**
