### PR TITLE
Let tasks expire via WQ mechanisms when proxy dies.

### LINKED ISSUE #40: specify_end_time for proxy timeout
We need to implement and test Ben's fix for tasks running through foreman that fail because the proxy has expired.  See his email below.

```
Hi all,

We are testing a new feature that expires tasks if they do not complete by a certain deadline. The use case is to detect when the task fails because the globus proxy has expired. In lobster code, you would add something like:

wq.specify_end_time(task, seconds)

In which seconds is the deadline of the task, given in seconds since the Unix Epoch (e.g., int(time.time()).

When a task returns, you can check for an expired timeout as:

task = wq.wait(..)

if task:
    if(task.result | wq.WORK_QUEUE_RESULT_TASK_TIMEOUT):
         .....

Ben
```

### PR DESCRIPTION
**Pull request by matz-e**
Fixes #40.  Maybe we should terminate lobster though if no jobs with a
valid proxy can be created?  Or notify the user otherwise?  I see lots of tasks returning with exit code 32 ATM.

### CODE REVIEW

**Comment by matz-e** [comment]
Now shows the returned tasks like this:
```
2015-10-12 07:37:47 [INFO] lobster.cmssw.job: received the following task(s):
returned with status 0: 317
returned with status 8020: 879, 1099, 1115, 1118, 1123, 1125, 1181, 1506
parameters and logs in:
	/tmpscratch/users/matze/test_shuffle_take9/SingleMu_2012A_06Aug/failed/0000/0879
	/tmpscratch/users/matze/test_shuffle_take9/SingleMu_2012A_06Aug/failed/0000/1099
	/tmpscratch/users/matze/test_shuffle_take9/SingleMu_2012A_06Aug/failed/0000/1115
	/tmpscratch/users/matze/test_shuffle_take9/SingleMu_2012A_06Aug/failed/0000/1118
	/tmpscratch/users/matze/test_shuffle_take9/SingleMu_2012A_06Aug/failed/0000/1123
	/tmpscratch/users/matze/test_shuffle_take9/SingleMu_2012A_06Aug/failed/0000/1125
	/tmpscratch/users/matze/test_shuffle_take9/SingleMu_2012A_06Aug/failed/0000/1181
	/tmpscratch/users/matze/test_shuffle_take9/SingleMu_2012A_06Aug/failed/0000/1506
failed due to timed out: 2140, 2141
parameters and logs in:
	/tmpscratch/users/matze/test_shuffle_take9/SingleMu_2012A_06Aug/failed/0000/2140
	/tmpscratch/users/matze/test_shuffle_take9/SingleMu_2012A_06Aug/failed/0000/2141
```

**Comment by annawoodard** [comment]
> Maybe we should terminate lobster though if no jobs with a
valid proxy can be created? Or notify the user otherwise?

I vote that we terminate lobster if no jobs with a valid proxy can be created. Nothing useful can be done otherwise, it just adds another layer of understanding required of the user to fix the problem.

**Comment by annawoodard** [comment]
Should we open that as a separate issue, or add to this PR?

**Comment by matz-e** [comment]
I'd maybe pull this in here.  I can take care of it + resolving the merge conflict.

**Comment by annawoodard** [comment]
Sounds good.

**Pull request merged**
