### PR TITLE
Add build to .gitignore

### PR DESCRIPTION
**Pull request by PerilousApricot**
Prevent pip's build directory from marking the repo dirty

### CODE REVIEW

**Comment by annawoodard** [comment]
Thanks for putting this together, @PerilousApricot!!

This change good to me for merging, but for my own education about pip voodoo, does anyone know why this wouldn't affect everyone? Starting from a clean source checkout in `~/lobster`:

```
[earth] ~/lobster >echo $CMSSW_BASE
/afs/crc.nd.edu/user/a/awoodard/releases/CMSSW_8_0_15
[earth] ~/lobster >rm -rf ~/.lobster
[earth] ~/lobster >virtualenv --system-site-packages ~/.lobster
(.lobster) [earth] ~/lobster >. ~/.lobster/bin/activate
(.lobster) [earth] ~/lobster >cd ~/lobster
(.lobster) [earth] ~/lobster >./install_dependencies.sh
(.lobster) [earth] ~/lobster >pip install .
[...]
Successfully installed Lobster-1.5-f4074a6-clean docutils-0.13.1 elasticsearch-5.2.0 elasticsearch-dsl-5.1.0 httplib2-0.10.3 lockfile-0.12.2 nose-1.3.7 protobuf-3.2.0 psutil-5.1.3 python-cjson-1.1.0 python-daemon-2.1.2 pyxdg-0.25 requests-2.13.0 retrying-1.3.3 snakebite-1.3.13 urllib3-1.20
```

I only get the `build` directory if I run `easy_install .`, but even then the repo is still marked clean.

**Comment by matz-e** [comment]
Are there any implications by having a `build` directory around? I remember having some troubleshooting where this was the source of issues and had to be deleted to get everything running nice.

It would be nice if the Lobster install (version number printed in the logs when Lobster starts up) would be marked as clean by this, though, if `build` is created by `pip`.

**Comment by annawoodard** [comment]
I remember the build issue. Hmm, that's a bad feeling, when you vaguely remember a problem but not the lesson you learned about its cause 😞 . 

It's still not clear to me why my build directory does not get the install version marked dirty. But I'm happy to chalk it up to pip voodoo, merge, and keep marching forward. If anyone figures it out, please let us know!

Thanks again @PerilousApricot!!

**Comment by matz-e** [comment]
Actually, the initial version may get tagged by `setup.py` before `pip` does anything. The next time around, `setup.py` will see the directory…

**Comment by annawoodard** [comment]
I tried installing again after the build directory had been created, and for me it was still marked clean.

**Comment by matz-e** [comment]
Weird…

**Comment by annawoodard** [comment]
👻 👻👻👻👻👻👻👻👻👻👻👻👻👻
spooky

**Comment by PerilousApricot** [comment]
Warewolf bar mitzvah up in here

**Pull request merged**
