### PR TITLE
Mc plotting updates

### PR DESCRIPTION
**Pull request by matz-e**
Updates the MC generation config to 76, and fixes two minor monitoring issues. More to come…

### CODE REVIEW

**Comment by annawoodard** [comment]
:clap: :clap: :clap: 
Awesome!

**Comment by annawoodard** [comment]
@matz-e: Sorry-- I should have tested before merging-- but trying your new MC configuration, I see:

```
  File "/afs/crc.nd.edu/user/a/awoodard/lobster/lobster/core/source.py", line 182, in __init__
    wflow.setup(self.workdir, self.basedirs)
  File "/afs/crc.nd.edu/user/a/awoodard/lobster/lobster/core/workflow.py", line 332, in setup
    self.determine_outputs(basedirs)
  File "/afs/crc.nd.edu/user/a/awoodard/lobster/lobster/core/workflow.py", line 307, in determine_outputs
    source = imp.load_source('cms_config_source', self.pset, f)
  File "mc_gen/HIG-RunIIFall15MiniAODv2-00224_1_cfg.py", line 88, in <module>
    process.Flag_chargedHadronTrackResolutionFilter = cms.Path(process.chargedHadronTrackResolutionFilter)
AttributeError: 'Process' object has no attribute 'chargedHadronTrackResolutionFilter'
```

**Comment by matz-e** [comment]
@annawoodard: weird, it runs fine for me: http://www.crc.nd.edu/~mwolf3/lobster/test_mc_take29/

The shell script may actually have silent das errors that may mis-configure some steps (ran into that a few times). We could compare resulting configs (mine are in `~mwolf3/work/lobster/examples/mc_gen`).

**Comment by matz-e** [comment]
Hmm… assuming I found your pset, they seem to be identical.

**Comment by matz-e** [comment]
Ooooh… Which release are you using originally before you source lobster? I'm using my ttH work area, which is `7_6_3`…

**Comment by annawoodard** [comment]
Good catch, that is probably it! Maybe we should add a `cmsrel` and `cmsenv` at the top of the script so you can run it from any release and get the same result?

**Comment by annawoodard** [comment]
I will test and report back.

**Comment by matz-e** [comment]
I think the script(s) do the right thing… but what are you running Lobster with? Because it fails when trying to load a `7_6_3` script in the local Lobster instance.

**Comment by annawoodard** [comment]
> I think the script(s) do the right thing…

Wouldn't it be better if the script wasn't sensitive to what release you source it from?

I think I ran it with `CMSSW_7_6_1` but I will double check.

**Comment by matz-e** [comment]
The script is downloading a bunch of setup scripts, each creating and sourcing their own release before creating the config, I think.

The question is which release environment Lobster is running in, because ultimately, that determines what the configuration sees when we load it to determine the pset outputs.

**Pull request merged**
