### PR TITLE
Get WMCore from pypi

### PR DESCRIPTION
**Pull request by matz-e**
Additional changes on top of #569.

Closes #569.

Please make sure that the following items are taken care of if needed:

- [x] Has the database format changed? (renamed or new columns, tables)
  Or did any of the project layout change? (files required to run the
  workflows)
  - Please increase the version number `VERSION` after the imports in
    `lobster.util`.  This will ensure that Lobster does not try to load old
    projects with an incompatible version.
- [x] Did the required _Work Queue_ version change?
  - Please update the *two* version numbers in `doc/install.rst`.  If a new
    `cctools` tarball is available, please update that, too.
- [x] Are all additional dependencies in `setup.py`?
- [x] [Mark any issues as closed either in commits or in this pull
  request.](https://help.github.com/articles/closing-issues-via-commit-messages/)

### CODE REVIEW

**Comment by matz-e** [comment]
screenshot 2017-03-21 08 02 59

This obviously needs some tuning, still.

**Comment by matz-e** [comment]
W00t! We can request reviews now! @annawoodard would you please do me the favor? I've pushed that last commit to decrease the amount of time the dashboard updates take, will update with a plot in an hour or so.

**Comment by matz-e** [comment]
The old order has been restored:
screenshot 2017-03-21 13 27 00

**Comment by annawoodard** [comment]
Awesome work, @PerilousApricot and @matz-e! Thanks guys for implementing this!

👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏

**Pull request merged**
