### PR TITLE
User fixes

### LINKED ISSUE #77: Need to be able to resume moved working directories
Currently, lobster fails in all kinds of ways when a user moves the working directory and tries to resume working with it, e.g., by plotting from it.

### LINKED ISSUE #84: Make a copy of extra inputs.
We currently keep a copy of the cmssw pset, but not any other extra inputs which are specified in the configuration. I think that we should do so. If there is a good reason not to, then we should at least save the full path to those files. This is related to #77, but I'd rather keep it separate.

### PR DESCRIPTION
**Pull request by matz-e**
Just putting this out there.  Validation is broken if the user does not specify output files in the configuration.  This will save an expanded configuration to the working directory, containing output files and global tags.

For complete user-friendliness, the following still have to be addressed, at least partially:

- [ ] #28 
- [x] Fixes #84 
- [x] Fixes #77

### CODE REVIEW

**Comment by annawoodard** [comment]
@matz-e: do you want this reviewed and merged now, or after the to-do list is finished?

**Comment by matz-e** [comment]
I'd prefer to resolve at least #77, still. #28 is a hard one!

**Comment by matz-e** [comment]
@annawoodard: I think this should be ready, #28 is too big in scope to be really addressed here? Note that changes to the configuration need to be done to the configuration in the working directory, not the one passed on the command line.

**Comment by annawoodard** [comment]
Looks great!

**Pull request merged**
